server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    location /api/users {
        proxy_pass http://user-service:8081;
    }
    location /api/products {
        proxy_pass http://product-service:8082;
    }
    location /api/orders {
        proxy_pass http://order-service:8083;
    }
    location /api/cart {
        proxy_pass http://cart-service:8084;
    }
    location /api/payments {
        proxy_pass http://payment-service:8085;
    }
}
